export const COMPETITION_TEXT = {
  overviewEyebrow: "Navegación pública",
  overviewTitle: "Ligas y competiciones",
  overviewDescription:
    "PronostIA expone solo competiciones autorizadas y la disponibilidad diaria persistida por el backend.",
  filtersTitle: "Filtros de competición",
  filtersDescription:
    "Selecciona una competición o filtra partidos por equipo sin recalcular datos del backend.",
  competitionLabel: "Competición",
  teamLabel: "Equipo",
  allCompetitions: "Todas las competiciones",
  allTeams: "Todos los equipos",
  selectCompetition: "Selecciona una competición",
  clearFilters: "Limpiar filtros",
  fixturesCount: "Partidos disponibles",
  predictionsCount: "Pronósticos disponibles",
  latestRun: "Última ejecución",
  lastUpdated: "Última actualización",
  currentWindow: "Ventana diaria consultada",
  viewCompetition: "Ver competición",
  competitionUnavailableTitle: "Competición no disponible",
  competitionUnavailableDescription:
    "La competición solicitada no está habilitada o no existe en la disponibilidad pública actual.",
  emptyCompetitionTitle: "No hay partidos para esta competición",
  emptyCompetitionDescription:
    "PronostIA solo muestra partidos persistidos dentro de la ventana diaria activa.",
  emptyTeamTitle: "No hay partidos para el equipo seleccionado",
  emptyTeamDescription:
    "No encontramos partidos persistidos para el equipo filtrado dentro de la competición elegida.",
  predictionAvailable: "Pronóstico disponible",
  predictionUnavailable: "Pronóstico no disponible",
  openPrediction: "Ver pronóstico",
  historicalBadge: "Datos históricos",
  upcomingBadge: "Próximos partidos",
  unavailableDate: "Fecha no disponible",
  currentView: "Vista actual",
  statusAvailable: "Con partidos disponibles",
  statusPredictions: "Con pronósticos disponibles",
  statusEmpty: "Sin partidos en la ventana actual",
  resultsLabel: "Partidos encontrados",
  seasonLabel: "Temporada",
  backToDashboard: "Volver al dashboard",
  backToCompetitions: "Volver a competiciones",
  fixtureMeta: {
    kickoff: "Kickoff",
    status: "Estado",
    market: "Mercado principal",
    selection: "Selección principal",
    confidence: "Confidence",
    recommendation: "Recomendación",
  },
  statusLabels: {
    NS: "Programado",
    TBD: "Por confirmar",
    LIVE: "En vivo",
    HT: "Entretiempo",
    FT: "Finalizado",
    PST: "Postergado",
    CANC: "Cancelado",
  },
};
