export const COMPETITION_DEFINITIONS = [
  {
    key: "laliga",
    displayName: "LaLiga",
    geographyLabel: "España",
    countryValue: "Spain",
    regionValue: null,
    type: "DOMESTIC_LEAGUE",
    groupKey: "domesticLeagues",
    typeLabel: "Liga nacional",
  },
  {
    key: "premier-league",
    displayName: "Premier League",
    geographyLabel: "Inglaterra",
    countryValue: "England",
    regionValue: null,
    type: "DOMESTIC_LEAGUE",
    groupKey: "domesticLeagues",
    typeLabel: "Liga nacional",
  },
  {
    key: "ligue-1",
    displayName: "Ligue 1",
    geographyLabel: "Francia",
    countryValue: "France",
    regionValue: null,
    type: "DOMESTIC_LEAGUE",
    groupKey: "domesticLeagues",
    typeLabel: "Liga nacional",
  },
  {
    key: "serie-a-italy",
    displayName: "Serie A",
    geographyLabel: "Italia",
    countryValue: "Italy",
    regionValue: null,
    type: "DOMESTIC_LEAGUE",
    groupKey: "domesticLeagues",
    typeLabel: "Liga nacional",
  },
  {
    key: "bundesliga",
    displayName: "Bundesliga",
    geographyLabel: "Alemania",
    countryValue: "Germany",
    regionValue: null,
    type: "DOMESTIC_LEAGUE",
    groupKey: "domesticLeagues",
    typeLabel: "Liga nacional",
  },
  {
    key: "liga-profesional-arg",
    displayName: "Liga Profesional Argentina",
    geographyLabel: "Argentina",
    countryValue: "Argentina",
    regionValue: null,
    type: "DOMESTIC_LEAGUE",
    groupKey: "domesticLeagues",
    typeLabel: "Liga nacional",
  },
  {
    key: "serie-a-brazil",
    displayName: "Brasileirão Série A",
    geographyLabel: "Brasil",
    countryValue: "Brazil",
    regionValue: null,
    type: "DOMESTIC_LEAGUE",
    groupKey: "domesticLeagues",
    typeLabel: "Liga nacional",
  },
  {
    key: "copa-del-rey",
    displayName: "Copa del Rey",
    geographyLabel: "España",
    countryValue: "Spain",
    regionValue: null,
    type: "DOMESTIC_CUP",
    groupKey: "domesticCups",
    typeLabel: "Copa nacional",
  },
  {
    key: "fa-cup",
    displayName: "FA Cup",
    geographyLabel: "Inglaterra",
    countryValue: "England",
    regionValue: null,
    type: "DOMESTIC_CUP",
    groupKey: "domesticCups",
    typeLabel: "Copa nacional",
  },
  {
    key: "coupe-de-france",
    displayName: "Coupe de France",
    geographyLabel: "Francia",
    countryValue: "France",
    regionValue: null,
    type: "DOMESTIC_CUP",
    groupKey: "domesticCups",
    typeLabel: "Copa nacional",
  },
  {
    key: "coppa-italia",
    displayName: "Coppa Italia",
    geographyLabel: "Italia",
    countryValue: "Italy",
    regionValue: null,
    type: "DOMESTIC_CUP",
    groupKey: "domesticCups",
    typeLabel: "Copa nacional",
  },
  {
    key: "dfb-pokal",
    displayName: "DFB-Pokal",
    geographyLabel: "Alemania",
    countryValue: "Germany",
    regionValue: null,
    type: "DOMESTIC_CUP",
    groupKey: "domesticCups",
    typeLabel: "Copa nacional",
  },
  {
    key: "copa-argentina",
    displayName: "Copa Argentina",
    geographyLabel: "Argentina",
    countryValue: "Argentina",
    regionValue: null,
    type: "DOMESTIC_CUP",
    groupKey: "domesticCups",
    typeLabel: "Copa nacional",
  },
  {
    key: "copa-do-brasil",
    displayName: "Copa do Brasil",
    geographyLabel: "Brasil",
    countryValue: "Brazil",
    regionValue: null,
    type: "DOMESTIC_CUP",
    groupKey: "domesticCups",
    typeLabel: "Copa nacional",
  },
  {
    key: "uefa-champions-league",
    displayName: "UEFA Champions League",
    geographyLabel: "Europa",
    countryValue: null,
    regionValue: "Europe",
    type: "CONTINENTAL_CUP",
    groupKey: "continentalCups",
    typeLabel: "Competición internacional",
  },
  {
    key: "uefa-europa-league",
    displayName: "UEFA Europa League",
    geographyLabel: "Europa",
    countryValue: null,
    regionValue: "Europe",
    type: "CONTINENTAL_CUP",
    groupKey: "continentalCups",
    typeLabel: "Competición internacional",
  },
  {
    key: "conmebol-libertadores",
    displayName: "Copa Libertadores",
    geographyLabel: "Sudamérica",
    countryValue: null,
    regionValue: "South America",
    type: "CONTINENTAL_CUP",
    groupKey: "continentalCups",
    typeLabel: "Competición internacional",
  },
  {
    key: "conmebol-sudamericana",
    displayName: "Copa Sudamericana",
    geographyLabel: "Sudamérica",
    countryValue: null,
    regionValue: "South America",
    type: "CONTINENTAL_CUP",
    groupKey: "continentalCups",
    typeLabel: "Competición internacional",
  },
];
