export const COMPETITION_TEXT = {
  overviewEyebrow: "Navegación pública",
  overviewTitle: "Ligas y competiciones",
  overviewDescription:
    "PronostIA expone solo competiciones autorizadas y la disponibilidad diaria persistida por el backend.",
  filtersTitle: "Filtros de competición",
  filtersDescription:
    "Navega por tipo, país o región, competición y equipo sin recalcular datos del backend.",
  typeLabel: "Tipo de competición",
  geographyLabel: "País o región",
  competitionLabel: "Competición",
  teamLabel: "Equipo",
  allTypes: "Todas las categorías",
  allGeographies: "Todos los países y regiones",
  allCompetitions: "Todas las competiciones",
  allTeams: "Todos los equipos",
  selectCompetition: "Selecciona una competición",
  clearFilters: "Limpiar filtros",
  fixturesCount: "Partidos disponibles",
  predictionsCount: "Pronósticos disponibles",
  fixturesMetricLabel: "Partidos",
  predictionsMetricLabel: "Pronósticos",
  coverageMetricLabel: "Cobertura",
  competitionsCountSuffix: "competiciones",
  latestRun: "Última ejecución",
  lastUpdated: "Última actualización",
  currentWindow: "Ventana diaria consultada",
  viewCompetition: "Ver competición",
  currentBadge: "Actual",
  selectedBadge: "Seleccionada",
  competitionUnavailableTitle: "Competición no disponible",
  competitionUnavailableDescription:
    "La competición solicitada no está habilitada o no existe en la disponibilidad pública actual.",
  emptyCompetitionTitle: "No hay partidos para esta competición",
  emptyCompetitionDescription:
    "PronostIA solo muestra partidos persistidos dentro de la ventana diaria activa.",
  emptyTeamTitle: "No hay partidos para el equipo seleccionado",
  emptyTeamDescription:
    "No encontramos partidos persistidos para el equipo filtrado dentro de la competición elegida.",
  emptyCatalogTitle: "Sin datos disponibles",
  emptyCatalogDescription:
    "No encontramos competiciones para la combinación de filtros actual.",
  predictionAvailable: "Pronóstico disponible",
  predictionUnavailable: "Pronóstico no disponible",
  openPrediction: "Ver pronóstico",
  historicalBadge: "Datos históricos",
  upcomingBadge: "Próximos partidos",
  unavailableDate: "Fecha no disponible",
  statusAvailable: "Partidos disponibles",
  statusPredictions: "Pronósticos disponibles",
  statusEmpty: "Sin partidos hoy",
  statusHistoricalOnly: "Datos históricos",
  statusCoveragePartial: "Cobertura parcial",
  statusAccessLimited: "Acceso limitado",
  resultsLabel: "Partidos encontrados",
  seasonLabel: "Temporada",
  unavailableValue: "No disponible",
  backToDashboard: "Volver al dashboard",
  backToCompetitions: "Volver a competiciones",
  availabilityLabel: "Disponibilidad",
  typeLabels: {
    DOMESTIC_LEAGUE: "Liga nacional",
    DOMESTIC_CUP: "Copa nacional",
    CONTINENTAL_CUP: "Competición internacional",
  },
  groupLabels: {
    domesticLeagues: "Ligas nacionales",
    domesticCups: "Copas nacionales",
    continentalCups: "Competiciones internacionales",
  },
  availabilityLabels: {
    VERIFIED: "Verificada",
    PARTIAL: "Disponibilidad parcial",
    PLAN_RESTRICTED: "Acceso limitado por el proveedor",
    NOT_AVAILABLE: "Sin datos disponibles",
    INCONCLUSIVE: "Sin datos disponibles",
  },
  availabilityDescriptions: {
    VERIFIED: "La identidad y la cobertura observada son consistentes.",
    PARTIAL:
      "PronostIA muestra esta competición, pero la cobertura vigente del proveedor puede ser parcial.",
    PLAN_RESTRICTED:
      "El proveedor limita parte de la cobertura disponible para esta competición en el plan actual.",
    NOT_AVAILABLE:
      "No encontramos datos públicos suficientes para esta competición en la ventana actual.",
    INCONCLUSIVE:
      "La disponibilidad vigente de esta competición sigue siendo inconclusa.",
  },
  coverageValues: {
    VERIFIED: "Verificada",
    PARTIAL: "Parcial",
    PLAN_RESTRICTED: "Limitado",
    NOT_AVAILABLE: "No disponible",
    INCONCLUSIVE: "No disponible",
  },
  fixtureMeta: {
    kickoff: "Kickoff",
    status: "Estado",
    market: "Mercado principal",
    selection: "Selección principal",
    confidence: "Confidence",
    recommendation: "Recomendación",
  },
  statusLabels: {
    NS: "Programado",
    TBD: "Por confirmar",
    LIVE: "En vivo",
    HT: "Entretiempo",
    FT: "Finalizado",
    PST: "Postergado",
    CANC: "Cancelado",
  },
};
